### ISSUE TITLE
Implement Word/Phrase Blacklist

### ISSUE THREAD

**Issue by dadirta** [dadirta/lahujDiscordBot#3]

**Comment by krazedkat** [comment]
Functionality added in commit [635042c3a5fc23e70b3fadd8230e8df4a6170451](https://github.com/dadirta/lahujDiscordBot/commit/635042c3a5fc23e70b3fadd8230e8df4a6170451).

**Comment by krazedkat** [comment]
Reopened as functionality is not yet fully fledged. Still need to add the ability to remove messages with blacklisted words, etc.

**Comment by dadirta** [comment]
Added the required features, however it needs to be tested and ironed out a bit before being considered complete.

**Comment by krazedkat** [comment]
Tested !blacklist and !remblacklist functionality. No obvious issues. Have yet to test purging.

**Comment by dadirta** [comment]
Everything seems to be working now. Closing.
