### ISSUE TITLE
Logout of Discord On Exit

### ISSUE THREAD

**Issue by dadirta** [dadirta/lahujDiscordBot#6]
Figuring this out would be nice, but not super important.

**Comment by krazedkat** [comment]
This is functionality already programmed into the discord.py API wrapper. Specifically, `client.run()` runs `client.logout()` when a `KeyboardException` is met. For more information, see the [discord.py documentation on client.run()](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.run) and the [discord.py implementation of client.run()](https://github.com/Rapptz/discord.py/blob/master/discord/client.py).

A commit has been made to the AtriTestBranch, commit [bea6fcf8c7baae2ac7ac805e6cb7f3ae4bbe5494](https://github.com/dadirta/lahujDiscordBot/commit/bea6fcf8c7baae2ac7ac805e6cb7f3ae4bbe5494), which allows this functionality to occur in Windows. Prior to this commit, the functionality should have been present in other operating systems. Once the issue present in this commit is resolved, it will be merged to master branch.

**Comment by krazedkat** [comment]
The remaining warning has been fixed as of commit [969ca0c9f166032216084da0e34c694c64890aa2](https://github.com/dadirta/lahujDiscordBot/commit/969ca0c9f166032216084da0e34c694c64890aa2) to AtriTestBranch. It will be merged to master after confirmation that it works.
